<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="9" ignored="18" total="55" passed="28">
  <reporter-output>
  </reporter-output>
  <suite name="ZhiShiChanQuanPingTai" duration-ms="367863" started-at="2020-08-07T01:30:51Z" finished-at="2020-08-07T01:36:59Z">
    <groups>
    </groups>
    <test name="BusinessEnvironment " duration-ms="367863" started-at="2020-08-07T01:30:51Z" finished-at="2020-08-07T01:36:59Z">
      <class name="com.testng.testcase.testOneDateAttest">
        <test-method status="PASS" signature="test0WordAttest()[pri:0, instance:com.testng.testcase.testOneDateAttest@146044d7]" name="test0WordAttest" duration-ms="5971" started-at="2020-08-07T01:30:54Z" finished-at="2020-08-07T01:31:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test0WordAttest -->
        <test-method status="PASS" signature="test1SearchWorldName()[pri:0, instance:com.testng.testcase.testOneDateAttest@146044d7]" name="test1SearchWorldName" duration-ms="306" started-at="2020-08-07T01:31:00Z" finished-at="2020-08-07T01:31:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1SearchWorldName -->
        <test-method status="PASS" signature="test2PngAttest()[pri:0, instance:com.testng.testcase.testOneDateAttest@146044d7]" name="test2PngAttest" duration-ms="5614" started-at="2020-08-07T01:31:00Z" finished-at="2020-08-07T01:31:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2PngAttest -->
        <test-method status="PASS" signature="test3SearchPngName()[pri:0, instance:com.testng.testcase.testOneDateAttest@146044d7]" name="test3SearchPngName" duration-ms="284" started-at="2020-08-07T01:31:06Z" finished-at="2020-08-07T01:31:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3SearchPngName -->
        <test-method status="PASS" signature="test4YinPinAttest()[pri:0, instance:com.testng.testcase.testOneDateAttest@146044d7]" name="test4YinPinAttest" duration-ms="5553" started-at="2020-08-07T01:31:06Z" finished-at="2020-08-07T01:31:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4YinPinAttest -->
        <test-method status="PASS" signature="test5YinPinSearchName()[pri:0, instance:com.testng.testcase.testOneDateAttest@146044d7]" name="test5YinPinSearchName" duration-ms="296" started-at="2020-08-07T01:31:12Z" finished-at="2020-08-07T01:31:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5YinPinSearchName -->
        <test-method status="PASS" signature="test6VideoAttest()[pri:0, instance:com.testng.testcase.testOneDateAttest@146044d7]" name="test6VideoAttest" duration-ms="5457" started-at="2020-08-07T01:31:12Z" finished-at="2020-08-07T01:31:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6VideoAttest -->
        <test-method status="PASS" signature="test7SearchVideoName()[pri:0, instance:com.testng.testcase.testOneDateAttest@146044d7]" name="test7SearchVideoName" duration-ms="286" started-at="2020-08-07T01:31:18Z" finished-at="2020-08-07T01:31:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test7SearchVideoName -->
        <test-method status="PASS" signature="test8OtherAttest()[pri:0, instance:com.testng.testcase.testOneDateAttest@146044d7]" name="test8OtherAttest" duration-ms="5457" started-at="2020-08-07T01:31:18Z" finished-at="2020-08-07T01:31:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test8OtherAttest -->
        <test-method status="PASS" signature="test9SearchPngName()[pri:0, instance:com.testng.testcase.testOneDateAttest@146044d7]" name="test9SearchPngName" duration-ms="2371" started-at="2020-08-07T01:31:23Z" finished-at="2020-08-07T01:31:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test9SearchPngName -->
      </class> <!-- com.testng.testcase.testOneDateAttest -->
      <class name="com.testng.testcase.testThreeDateAttest">
        <test-method status="PASS" signature="test1TimeScopeSearch()[pri:0, instance:com.testng.testcase.testThreeDateAttest@15d9bc04]" name="test1TimeScopeSearch" duration-ms="5946" started-at="2020-08-07T01:32:24Z" finished-at="2020-08-07T01:32:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1TimeScopeSearch -->
        <test-method status="PASS" signature="test2TimeScopeSearch()[pri:0, instance:com.testng.testcase.testThreeDateAttest@15d9bc04]" name="test2TimeScopeSearch" duration-ms="6512" started-at="2020-08-07T01:32:30Z" finished-at="2020-08-07T01:32:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2TimeScopeSearch -->
        <test-method status="PASS" signature="test3TimeScopeSearch()[pri:0, instance:com.testng.testcase.testThreeDateAttest@15d9bc04]" name="test3TimeScopeSearch" duration-ms="6503" started-at="2020-08-07T01:32:37Z" finished-at="2020-08-07T01:32:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3TimeScopeSearch -->
        <test-method status="PASS" signature="test4TimeScopeSearch()[pri:0, instance:com.testng.testcase.testThreeDateAttest@15d9bc04]" name="test4TimeScopeSearch" duration-ms="6502" started-at="2020-08-07T01:32:43Z" finished-at="2020-08-07T01:32:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4TimeScopeSearch -->
        <test-method status="PASS" signature="test5ViewDetails()[pri:0, instance:com.testng.testcase.testThreeDateAttest@15d9bc04]" name="test5ViewDetails" duration-ms="9914" started-at="2020-08-07T01:32:50Z" finished-at="2020-08-07T01:33:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5ViewDetails -->
        <test-method status="PASS" signature="test6DeleteData()[pri:0, instance:com.testng.testcase.testThreeDateAttest@15d9bc04]" name="test6DeleteData" duration-ms="6234" started-at="2020-08-07T01:33:00Z" finished-at="2020-08-07T01:33:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6DeleteData -->
      </class> <!-- com.testng.testcase.testThreeDateAttest -->
      <class name="com.testng.testcase.testTwoDataAttest">
        <test-method status="FAIL" signature="test1TypeSelect()[pri:0, instance:com.testng.testcase.testTwoDataAttest@1e9e725a]" name="test1TypeSelect" duration-ms="12300" started-at="2020-08-07T01:31:26Z" finished-at="2020-08-07T01:31:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [存证条目（条）：1] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [存证条目（条）：1] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.testcase.testTwoDataAttest.test1TypeSelect(testTwoDataAttest.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1TypeSelect -->
        <test-method status="FAIL" signature="test2TypeSelect()[pri:0, instance:com.testng.testcase.testTwoDataAttest@1e9e725a]" name="test2TypeSelect" duration-ms="11595" started-at="2020-08-07T01:31:38Z" finished-at="2020-08-07T01:31:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [存证条目（条）：1] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [存证条目（条）：1] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.testcase.testTwoDataAttest.test2TypeSelect(testTwoDataAttest.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2TypeSelect -->
        <test-method status="FAIL" signature="test3TypeSelect()[pri:0, instance:com.testng.testcase.testTwoDataAttest@1e9e725a]" name="test3TypeSelect" duration-ms="11682" started-at="2020-08-07T01:31:50Z" finished-at="2020-08-07T01:32:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [存证条目（条）：1] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [存证条目（条）：1] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.testcase.testTwoDataAttest.test3TypeSelect(testTwoDataAttest.java:114)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3TypeSelect -->
        <test-method status="FAIL" signature="test4TypeSelect()[pri:0, instance:com.testng.testcase.testTwoDataAttest@1e9e725a]" name="test4TypeSelect" duration-ms="11592" started-at="2020-08-07T01:32:01Z" finished-at="2020-08-07T01:32:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [存证条目（条）：1] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [存证条目（条）：1] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.testcase.testTwoDataAttest.test4TypeSelect(testTwoDataAttest.java:146)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4TypeSelect -->
        <test-method status="FAIL" signature="test5TypeSelect()[pri:0, instance:com.testng.testcase.testTwoDataAttest@1e9e725a]" name="test5TypeSelect" duration-ms="11530" started-at="2020-08-07T01:32:13Z" finished-at="2020-08-07T01:32:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [存证条目（条）：1] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [存证条目（条）：1] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.testcase.testTwoDataAttest.test5TypeSelect(testTwoDataAttest.java:180)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5TypeSelect -->
      </class> <!-- com.testng.testcase.testTwoDataAttest -->
      <class name="com.testng.testcase.testFourDateAttest">
        <test-method status="PASS" signature="test1BatchAttest()[pri:0, instance:com.testng.testcase.testFourDateAttest@473b46c3]" name="test1BatchAttest" duration-ms="11101" started-at="2020-08-07T01:33:06Z" finished-at="2020-08-07T01:33:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1BatchAttest -->
        <test-method status="PASS" signature="test3InformationVerification()[pri:0, instance:com.testng.testcase.testFourDateAttest@473b46c3]" name="test3InformationVerification" duration-ms="726" started-at="2020-08-07T01:33:17Z" finished-at="2020-08-07T01:33:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3InformationVerification -->
        <test-method status="PASS" signature="test4DeleteDatas()[pri:0, instance:com.testng.testcase.testFourDateAttest@473b46c3]" name="test4DeleteDatas" duration-ms="3251" started-at="2020-08-07T01:33:18Z" finished-at="2020-08-07T01:33:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4DeleteDatas -->
        <test-method status="PASS" signature="test5UpdateDataAttest()[pri:0, instance:com.testng.testcase.testFourDateAttest@473b46c3]" name="test5UpdateDataAttest" duration-ms="6043" started-at="2020-08-07T01:33:21Z" finished-at="2020-08-07T01:33:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5UpdateDataAttest -->
        <test-method status="PASS" signature="test6PageData()[pri:0, instance:com.testng.testcase.testFourDateAttest@473b46c3]" name="test6PageData" duration-ms="1833" started-at="2020-08-07T01:33:27Z" finished-at="2020-08-07T01:33:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6PageData -->
      </class> <!-- com.testng.testcase.testFourDateAttest -->
      <class name="com.testng.testcase.testTwoProcessEvidence">
        <test-method status="PASS" signature="test1TimeSearchData()[pri:0, instance:com.testng.testcase.testTwoProcessEvidence@3c0a50da]" name="test1TimeSearchData" duration-ms="12856" started-at="2020-08-07T01:36:28Z" finished-at="2020-08-07T01:36:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1TimeSearchData -->
        <test-method status="FAIL" signature="test2TimeSearchData()[pri:0, instance:com.testng.testcase.testTwoProcessEvidence@3c0a50da]" name="test2TimeSearchData" duration-ms="2473" started-at="2020-08-07T01:36:41Z" finished-at="2020-08-07T01:36:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [共 3 条] but found [共 1 条]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [共 3 条] but found [共 1 条]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.testcase.testTwoProcessEvidence.test2TimeSearchData(testTwoProcessEvidence.java:89)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2TimeSearchData -->
        <test-method status="FAIL" signature="test3TimeSearchData()[pri:0, instance:com.testng.testcase.testTwoProcessEvidence@3c0a50da]" name="test3TimeSearchData" duration-ms="12402" started-at="2020-08-07T01:36:44Z" finished-at="2020-08-07T01:36:56Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at com.testng.testcase.testTwoProcessEvidence.test3TimeSearchData(testTwoProcessEvidence.java:115)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3TimeSearchData -->
        <test-method status="FAIL" signature="test4TimeSearchData()[pri:0, instance:com.testng.testcase.testTwoProcessEvidence@3c0a50da]" name="test4TimeSearchData" duration-ms="2412" started-at="2020-08-07T01:36:56Z" finished-at="2020-08-07T01:36:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [共 3 条] but found [共 1 条]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [共 3 条] but found [共 1 条]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.testcase.testTwoProcessEvidence.test4TimeSearchData(testTwoProcessEvidence.java:142)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4TimeSearchData -->
        <test-method status="FAIL" signature="test5NameSearchData()[pri:0, instance:com.testng.testcase.testTwoProcessEvidence@3c0a50da]" name="test5NameSearchData" duration-ms="478" started-at="2020-08-07T01:36:58Z" finished-at="2020-08-07T01:36:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [共 1 条] but found [共 3 条]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [共 1 条] but found [共 3 条]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.testcase.testTwoProcessEvidence.test5NameSearchData(testTwoProcessEvidence.java:165)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5NameSearchData -->
      </class> <!-- com.testng.testcase.testTwoProcessEvidence -->
      <class name="com.testng.testcase.testLogin">
        <test-method status="PASS" signature="ClearData()[pri:0, instance:com.testng.testcase.testLogin@59717824]" name="ClearData" is-config="true" duration-ms="2213" started-at="2020-08-07T01:30:33Z" finished-at="2020-08-07T01:30:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ClearData -->
        <test-method status="PASS" signature="startDriver()[pri:0, instance:com.testng.testcase.testLogin@59717824]" name="startDriver" is-config="true" duration-ms="15519" started-at="2020-08-07T01:30:36Z" finished-at="2020-08-07T01:30:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startDriver -->
        <test-method status="PASS" signature="loginTest1()[pri:0, instance:com.testng.testcase.testLogin@59717824]" name="loginTest1" duration-ms="2865" started-at="2020-08-07T01:30:51Z" finished-at="2020-08-07T01:30:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest1 -->
        <test-method status="PASS" signature="endDriver()[pri:0, instance:com.testng.testcase.testLogin@59717824]" name="endDriver" is-config="true" duration-ms="1598" started-at="2020-08-07T01:36:59Z" finished-at="2020-08-07T01:37:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endDriver -->
      </class> <!-- com.testng.testcase.testLogin -->
      <class name="com.testng.testcase.testOneProcessEvidence">
        <test-method status="PASS" signature="test1CancelProcessEvidence()[pri:0, instance:com.testng.testcase.testOneProcessEvidence@516be40f]" name="test1CancelProcessEvidence" duration-ms="16279" started-at="2020-08-07T01:33:29Z" finished-at="2020-08-07T01:33:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1CancelProcessEvidence -->
        <test-method status="PASS" signature="test2AddProcessEvidence()[pri:0, instance:com.testng.testcase.testOneProcessEvidence@516be40f]" name="test2AddProcessEvidence" duration-ms="25001" started-at="2020-08-07T01:33:45Z" finished-at="2020-08-07T01:34:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2AddProcessEvidence -->
        <test-method status="PASS" signature="test3CancelQueueProcessEvidence()[pri:0, instance:com.testng.testcase.testOneProcessEvidence@516be40f]" name="test3CancelQueueProcessEvidence" duration-ms="14619" started-at="2020-08-07T01:34:10Z" finished-at="2020-08-07T01:34:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3CancelQueueProcessEvidence -->
        <test-method status="PASS" signature="test4ProcessEvidenceDetails()[pri:0, instance:com.testng.testcase.testOneProcessEvidence@516be40f]" name="test4ProcessEvidenceDetails" duration-ms="109544" started-at="2020-08-07T01:34:25Z" finished-at="2020-08-07T01:36:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4ProcessEvidenceDetails -->
        <test-method status="PASS" signature="test5DownloadProcessEnvidence()[pri:0, instance:com.testng.testcase.testOneProcessEvidence@516be40f]" name="test5DownloadProcessEnvidence" duration-ms="13930" started-at="2020-08-07T01:36:14Z" finished-at="2020-08-07T01:36:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5DownloadProcessEnvidence -->
      </class> <!-- com.testng.testcase.testOneProcessEvidence -->
    </test> <!-- BusinessEnvironment  -->
  </suite> <!-- ZhiShiChanQuanPingTai -->
</testng-results>
